version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:9
    working_directory: ~/repo

    environment:
      COVERALLS_REPO_TOKEN: 2xA4TIqqxVf1yNknI6CCrgmReVBMIc168
      CC_TEST_REPORTER_ID: 40be9c9a6468745b257f8404dcf1e60ddcad486130b1684d4a2dbbc344742c9e

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
                     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                     chmod +x ./cc-test-reporter

      - run: ./cc-test-reporter before-build

      - run: ./gradlew build sonarqube

      - run: ./cc-test-reporter after-build --coverage-input-type jacoco --exit-code $?

      - store_test_results:
          path: build/test-results/test/

      - run: ./gradlew jacocoTestReport coveralls

      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
