version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9
    working_directory: ~/repo

    environment:
      COVERALLS_REPO_TOKEN: 2xA4TIqqxVf1yNknI6CCrgmReVBMIc168
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew test

      - store_test_results:
          path: build/test-results/test/

      - run: ./gradlew jacocoTestReport coveralls

#      - run: ./gradlew bintrayUpload