name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: clean build jacocoTestReport sonarqube --info --warning-mode=all
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
